In [7]:
from tensorflow import keras
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False  # 마이너스 표시 해결
# 한글설정
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # windows 사용자
# matplotlib.rcParams['font.family'] = 'AppleGothic Gothic' # Mac사용자
matplotlib.rcParams['font.size'] = '10' # 글자크기

In [8]:
(train_input,train_target),(test_input,test_target) = keras.datasets.fashion_mnist.load_data()
train_scaled = train_input/255.0

In [9]:
train_scaled,val_scaled,train_target,val_target = train_test_split(
    train_scaled,train_target,test_size=0.2,random_state=42
)

In [10]:
model = keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(28,28))) # 
model.add(keras.layers.Dense(100,activation='relu')) # sigmoid
model.add(keras.layers.Dropout(0.3)) # 30%를 제외시키는 규제적용
model.add(keras.layers.Dense(10,activation='softmax')) 

c:\Python312\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [11]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_1 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 100)            │        78,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 79,510 (310.59 KB)

 Trainable params: 79,510 (310.59 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
# model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
# # epochs 돌때마다 loss, accuracy 값을 저장
# # train_scaled, val_scaled 함께 훈련시킴
# history = model.fit(train_scaled, train_target, epochs=20, validation_data=(val_scaled, val_target))

In [17]:
model.load_weights('model0529.weights.h5')

In [19]:
model.predict(val_scaled)

375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


array([[9.4248843e-18, 4.2894666e-21, 7.6858500e-19, ..., 2.8917402e-09,
        1.0000000e+00, 1.0595324e-14],
       [1.2877310e-08, 1.1107080e-19, 6.6891326e-11, ..., 1.7368012e-13,
        1.0000000e+00, 1.7396381e-14],
       [4.4439469e-15, 2.3350964e-15, 2.4899554e-17, ..., 9.9987793e-01,
        2.9801450e-12, 6.2765736e-08],
       ...,
       [3.1437543e-07, 2.9839856e-17, 1.1210607e-09, ..., 2.4993190e-08,
        9.9999917e-01, 4.1623650e-08],
       [5.4447489e-13, 4.0210669e-17, 3.3554268e-15, ..., 1.7235038e-11,
        1.0000000e+00, 1.9764402e-15],
       [1.6807199e-02, 3.1031771e-11, 4.6159537e-05, ..., 1.4915694e-04,
        1.9745077e-09, 9.4910890e-01]], dtype=float32)

In [20]:
val_scaled

array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.00784314, 0.        , 0.43921569, ..., 0.        ,
         0.        , 0.00392157],
        [0.00784314, 0.        , 0.08235294, ..., 0.        ,
         0.00392157, 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0. 

In [21]:
val_target

array([8, 8, 7, ..., 8, 8, 1], dtype=uint8)

In [24]:
# model_weights 읽어와서 데이터 처리
val_labels = np.argmax(model.predict(val_scaled), axis=-1) 
np.mean(val_labels == val_target) # 가장 높은 값 중에 정답과 일치한 것만 평균으로 적용

375/375 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


0.88375

In [23]:
val_labels
# 마지막이 달라

array([8, 8, 7, ..., 8, 8, 9], dtype=int64)

In [26]:
# 모델 전체를 저장한 것을 불러와서 처리
model = keras.models.load_model('model_all.h5')

In [27]:
# model.evaluate(val_scaled, val_target)

375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8851 - loss: 0.3315


[0.32825955748558044, 0.8837500214576721]