# Python 복습

### Markdown 수식 작성
    - LaTEX 태그로 작성 가능 
$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    +
    \begin{pmatrix}
    5 & 5 & 5 \\
    5 & 5 & 5 \\
    \end{pmatrix}
$$
$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    \times
    \begin{pmatrix}
    5 & 5 \\
    5 & 5 \\
    5 & 5 \\
    \end{pmatrix}

$$

### Numpy
 - 데이터는 행렬로 표현(영상도 포함)
 - 선형대수/통계 연산을 위한 라이브러리
 
Pandas : 데이터 분석에 가장 많이 활용
Numpy : 알고리즘 활용에 numpy가 필수적 패키지

In [1]:
# 호출
import numpy as np

array broadcasting
- 차원이 다른 연산을 동일한 차원으로 자동으로 변경시켜 연산을 가능하게 해주는 것
- 딥러닝에서 bias(편향) 계산을 할 때 주로 사용

In [6]:
# array 생성
# ary = np.array(np.random.randint(10, 100, 10)) 

# 초기 가중치 생성
ary = np.array(np.random.randn(10)) # 표준정규분포를 따르는 난수 생성 -> 초기 가중치 생성 때 사용
ary

array([ 0.89956381,  0.26044436, -0.60357296, -0.6689896 , -0.7098007 ,
       -0.10944833,  1.12141567,  0.22148234, -1.4735925 ,  0.62985993])

In [7]:
# 편향값 생성
bias = np.random.rand(1) 
bias

array([0.67841703])

In [8]:
ary + bias # array broadcasting : 곱셈도 가능

array([ 1.57798084,  0.93886139,  0.07484408,  0.00942743, -0.03138367,
        0.5689687 ,  1.7998327 ,  0.89989938, -0.79517547,  1.30827697])

### 통계함수
 - max, min, mean, median, var, std

In [ ]:
np.

### random 모듈
 - sead : 랜던 모듈의 규칙값. 난수 생성 환경 고정
 - randint : 균등분포로 정수 생성
 - randn : 정규분포로 난수 생성
 - shuffle : 무작위 섞기
 - choice : 특정확률로 데이터 뽑기

seed

In [9]:
seed = 603 # 머신러닝, 딥러닝에서 하이퍼파라미터로 사용

np.random.seed(seed)
r1 = np.random.rand(10)

np.random.seed(1)
r2 = np.random.rand(10)

np.random.seed(seed)
r3 = np.random.rand(10)


In [10]:
r1, r2, r3 # r1 = r3 ==> seed가 고정되었기 때문에, 단 다시 수행하면 같이 또 바껴

(array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]),
 array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
        3.96767474e-01, 5.38816734e-01]),
 array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]))

머신러닝 예시
- scaling 처리 후 return 값으로 ndarray 타입 데이터로 출력

In [2]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

x = np.random.randint(1,100,10).reshape(-1, 2) # reshape(-1, 2)에서 -1은 알아서 행 생성, 2는 2열을 의미 ==> 5행 2열 데이터 생성
df = pd.DataFrame(x)

df

0   1
0  64   5
1  31  86
2  15  95
3  55  59
4  70   6

In [4]:
# 정규화
scaled_data = MinMaxScaler().fit_transform(df)
scaled_data, type(scaled_data)

(array([[0.89090909, 0.        ],
        [0.29090909, 0.9       ],
        [0.        , 1.        ],
        [0.72727273, 0.6       ],
        [1.        , 0.01111111]]),
 numpy.ndarray)

In [9]:
# zero 행렬
zero_ary = np.zeros((4,4))
zero_ary # elements의 type : float ==> 메모리 잡아먹는 양이 커(int에 비해)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

머신러닝 예시
- 초기값을 임의로 생성하여 zero 생성하여 대입할 때 다음과 같은 행렬을 작성하시오(numpy 사용).
$$
 \begin{pmatrix}
 난수 & 0 & 0 & 0 \\
 0 & 난수 & 0 & 0 \\
 0 & 0 & 난수 & 0 \\
 0 & 0 & 0 & 난수 \\
 \end{pmatrix}

$$

In [19]:

array = np.array(np.random.randn(4))

for i in range(4):
    zero_ary[i][i] = array[i]
print(zero_ary)

[[3.02964921 0.         0.         0.        ]
 [0.         1.34122825 0.         0.        ]
 [0.         0.         0.68385086 0.        ]
 [0.         0.         0.         1.54005767]]


In [21]:
# tc

import numpy as np

w = np.random.rand(4)
shp = np.zeros((4,4))

for i in range(shp.shape[0]):
    for j in range(shp.shape[1]):
        if i == j : shp[i][j] = w[i]
shp


array([[0.73017248, 0.        , 0.        , 0.        ],
       [0.        , 0.77593326, 0.        , 0.        ],
       [0.        , 0.        , 0.38962367, 0.        ],
       [0.        , 0.        , 0.        , 0.4702694 ]])

In [23]:
# numpy에 대각행렬 생성 method가 있어
import numpy as np
diag_matrix = np.diag(np.random.rand(4))

diag_matrix

array([[0.01501785, 0.        , 0.        , 0.        ],
       [0.        , 0.99978577, 0.        , 0.        ],
       [0.        , 0.        , 0.03260245, 0.        ],
       [0.        , 0.        , 0.        , 0.96226372]])

### Function
- 반복성을 줄이고 함수로 선언한 연산을 재사용
- 객체 지향 언어의 가장 큰 장점

``` python
def 함수명(파라미터):
    return 출력값
```

In [25]:
# 리턴을 선언하지 않고 선언하는 경우 : 함수가 연산 도구로만 사용될 때
# 전역변수, 지역변수

num = 603 # 전역변수
print(num)

def today():
    num = 604 # 지역변수
    print(num)

today()

print(num)

603
604
603


In [26]:
num = 603 # 전역변수
print(num)

def today(): # 리턴 안함
    global num # 전역변수 지정
    num = 604 # 지역변수
    print(num)

today()
print('-'*10)
print(num)

603
604
----------
604


In [27]:
num = 603 # 전역변수
print(num)

def today(): # 리턴 안함
    global num # 전역변수 지정
    num = 604 # 지역변수
    print(num)

today()
print('-'*10)
num = 603
print(num)

603
604
----------
603
