In [48]:
# from sklearn import svm, metrics
# from sklearn.neighbors import KNeighborsClassifier # 분류
# from sklearn.neighbors import KNeighborsRegressor # 회귀-예측
from sklearn.linear_model import LinearRegression # 선형회귀
from sklearn.preprocessing import PolynomialFeatures # 다항특성을 만들어주는 라이브러리
from sklearn.model_selection import train_test_split # train_test_split : train data, test data를 나누는 함수
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # 한글설정
matplotlib.rcParams['font.size'] = 10 # 글자크기
matplotlib.rcParams['axes.unicode_minus'] = False # 마이너스 기호(-) 표기

In [49]:
import pandas as pd
df=pd.read_csv('https://bit.ly/fish_csv')
df

Species  Weight  Length  Diagonal   Height   Width
0     Bream   242.0    25.4      30.0  11.5200  4.0200
1     Bream   290.0    26.3      31.2  12.4800  4.3056
2     Bream   340.0    26.5      31.1  12.3778  4.6961
3     Bream   363.0    29.0      33.5  12.7300  4.4555
4     Bream   430.0    29.0      34.0  12.4440  5.1340
..      ...     ...     ...       ...      ...     ...
154   Smelt    12.2    12.2      13.4   2.0904  1.3936
155   Smelt    13.4    12.4      13.5   2.4300  1.2690
156   Smelt    12.2    13.0      13.8   2.2770  1.2558
157   Smelt    19.7    14.3      15.2   2.8728  2.0672
158   Smelt    19.9    15.0      16.2   2.9322  1.8792

[159 rows x 6 columns]

In [50]:
# 0. 데이터 확인 : 값 중 NaN/0 여부, 타입, 최소값/최대값, 값의 분포, 각 특성별 데이터 최대값 등 확인
# 1. 데이터 전처리 : data, target 분리
fish_target = df['Species'].to_numpy()
fish_input = df.iloc[:,1:].to_numpy()
# 1.1 train/test set 분리
# from sklearn import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    fish_input, fish_target, random_state=42
)
# 1.2 표준화 작업
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [51]:
# 2. 데이터 실습시키기
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_scaled, train_target)
# 정답률이 0.8067226890756303/0.85로 낮아 

LogisticRegression()

In [52]:
# 3. 데이터 예측
predict = lr.predict(test_scaled[:5])
print(predict)
# 기울기, y 절편의 값을 적용시켜서 z 점수 출력하고, softMax 함수를 적용시켜서 

['Perch' 'Smelt' 'Pike' 'Perch' 'Perch']


In [53]:
# 4. 데이터 정답률 - train/test
print(lr.score(train_scaled, train_target)) # 0.8067226890756303
print(lr.score(test_scaled, test_target)) # 0.85

# 과소적합

0.8067226890756303
0.85


In [54]:
# 정답률이 낮을 때 낮은 C규제값과 높은 max_iter로 정답률을 높일 수 있다.

# C : 규제, 값이 올가면 규제가 약해지고, 값이 낮으면 규제가 강해짐.
  # 선형회귀에서 규제는 alpha값으로 지정: 값이 높으면 규제강화, 
# max_iter : 반복횟수, 기본은 100
lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_scaled, train_target)
# 수정 후 정답률 0.9327731092436975/0.925로 상승

LogisticRegression(C=20, max_iter=1000)

In [55]:
# 3. 데이터 예측
predict = lr.predict(test_scaled[:5])
print(predict)
# 기울기, y 절편의 값을 적용시켜서 z 점수 출력하고, softMax 함수를 적용시켜서 

['Perch' 'Smelt' 'Pike' 'Roach' 'Perch']


In [56]:
# 4. 데이터 정답률 - train/test
print(lr.score(train_scaled, train_target)) # 0.9327731092436975
print(lr.score(test_scaled, test_target)) # 0.925

0.9327731092436975
0.925


In [62]:
lr.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Roach', 'Perch'], dtype=object)

In [63]:
proba = lr.predict_proba(test_scaled[:5])
print(np.round(proba, decimals=3))

[[0.    0.014 0.842 0.    0.135 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.934 0.015 0.016 0.   ]
 [0.011 0.034 0.305 0.006 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]


In [64]:
# [[0.    0.014 0.842 0.    0.135 0.007 0.003] => 모두 더한 값이 1이 되어야 함.
0+0.014+0.842+0+.135+.007+.003

1.001

In [57]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [58]:
##### 결과값 도출 형태 분석 #####

predict = lr.predict(test_scaled[:5])
print(predict)

['Perch' 'Smelt' 'Pike' 'Roach' 'Perch']


In [59]:
proba = lr.predict_proba(test_scaled[:5])
proba
np.round(proba, decimals=3)

array([[0.   , 0.014, 0.842, 0.   , 0.135, 0.007, 0.003],
       [0.   , 0.003, 0.044, 0.   , 0.007, 0.946, 0.   ],
       [0.   , 0.   , 0.034, 0.934, 0.015, 0.016, 0.   ],
       [0.011, 0.034, 0.305, 0.006, 0.567, 0.   , 0.076],
       [0.   , 0.   , 0.904, 0.002, 0.089, 0.002, 0.001]])

In [60]:
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision, decimals=2))

[[ -6.51   1.04   5.17  -2.76   3.34   0.35  -0.63]
 [-10.88   1.94   4.78  -2.42   2.99   7.84  -4.25]
 [ -4.34  -6.24   3.17   6.48   2.36   2.43  -3.87]
 [ -0.69   0.45   2.64  -1.21   3.26  -5.7    1.26]
 [ -6.4   -1.99   5.82  -0.13   3.5   -0.09  -0.7 ]]


In [61]:
from scipy.special import softmax

proba=softmax(decision, axis=1)
print(np.round(proba,decimals=3))

[[0.    0.014 0.842 0.    0.135 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.934 0.015 0.016 0.   ]
 [0.011 0.034 0.305 0.006 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]
